// Code generated by fabrica. DO NOT EDIT.
package resources

import (
	"fmt"

	"github.com/openchami/fabrica/pkg/codegen"
	v1 "github.com/user/firmware-manager/apis/hardware.fabrica.dev/v1"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.FirmwareImage{}); err != nil {
		return fmt.Errorf("failed to register FirmwareImage: %w", err)
	}
	if err := gen.RegisterResource(&v1.FirmwareUpdateJob{}); err != nil {
		return fmt.Errorf("failed to register FirmwareUpdateJob: %w", err)
	}

	return nil
}
