
// Generated by Fabrica dev
// Template: init/go.mod.tmpl
// Generated: 2026-05-01T12:12:00-07:00

module github.com/user/firmware-manager

go 1.21

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/spf13/cobra v1.7.0
	github.com/spf13/viper v1.16.0
)
