// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-04-29T17:10:53Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for UpdateJob resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /updatejobs (list all updatejobs)
//   - GET /updatejobs/{uid} (get specific UpdateJob)
//   - POST /updatejobs (create new UpdateJob)
//   - PUT /updatejobs/{uid} (update UpdateJob spec)
//   - PATCH /updatejobs/{uid} (patch UpdateJob spec)
//   - DELETE /updatejobs/{uid} (delete UpdateJob)
//   - PUT /updatejobs/{uid}/status (update UpdateJob status)
//   - PATCH /updatejobs/{uid}/status (patch UpdateJob status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadUpdateJob*/SaveUpdateJob*/DeleteUpdateJob*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadUpdateJobWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	v1 "github.com/example/fms-mvp/apis/example.fabrica.dev/v1"
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"

	"github.com/example/fms-mvp/internal/storage"
)

// GetUpdateJobs returns all UpdateJob resources
func GetUpdateJobs(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	updatejobs, err := storage.LoadAllUpdateJobs(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load updatejobs: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, updatejobs)
}

// GetUpdateJob returns a specific UpdateJob resource by UID
func GetUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateJob UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadUpdateJob() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	updateJob, err := storage.LoadUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateJob not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, updateJob)
}

// CreateUpdateJob creates a new UpdateJob resource
func CreateUpdateJob(w http.ResponseWriter, r *http.Request) {
	var req CreateUpdateJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("UpdateJob")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	updateJob := &v1.UpdateJob{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "UpdateJob",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	updateJob.Metadata = req.Metadata
	updateJob.Metadata.UID = uid
	now := time.Now()
	updateJob.Metadata.CreatedAt = now
	updateJob.Metadata.UpdatedAt = now

	// Set labels and annotations
	if updateJob.Metadata.Labels == nil {
		updateJob.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		updateJob.Metadata.Labels[k] = v
	}
	if updateJob.Metadata.Annotations == nil {
		updateJob.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		updateJob.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), updateJob); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveUpdateJob(r.Context(), updateJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateJob: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "UpdateJob", updateJob.Metadata.UID, updateJob.Metadata.Name, updateJob); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for UpdateJob %s: %v\n", updateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, updateJob)
}

// UpdateUpdateJob updates the spec of an existing UpdateJob resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //updatejobs/{uid}/status to update status.
func UpdateUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateJob UID is required"))
		return
	}

	updateJob, err := storage.LoadUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateJob not found: %w", err))
		return
	}

	var req UpdateUpdateJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		updateJob.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	updateJob.Spec = req.AsSpec()

	// Update labels and annotations
	if updateJob.Metadata.Labels == nil {
		updateJob.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		updateJob.Metadata.Labels[k] = v
	}
	if updateJob.Metadata.Annotations == nil {
		updateJob.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		updateJob.Metadata.Annotations[k] = v
	}

	// Update timestamp
	updateJob.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateJob(r.Context(), updateJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateJob: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": updateJob.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "UpdateJob", updateJob.Metadata.UID, updateJob.Metadata.Name, updateJob, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for UpdateJob %s: %v\n", updateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, updateJob)
}

// PatchUpdateJob patches an existing UpdateJob resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateJob UID is required"))
		return
	}

	updateJob, err := storage.LoadUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateJob not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(updateJob.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &updateJob.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	updateJob.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveUpdateJob(r.Context(), updateJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched UpdateJob: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": updateJob.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "UpdateJob", updateJob.Metadata.UID, updateJob.Metadata.Name, updateJob, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for UpdateJob %s: %v\n", updateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, updateJob)
}

// UpdateUpdateJobStatus updates only the status of a UpdateJob resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateUpdateJobStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateJob UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateJob not found: %w", err))
		return
	}

	var statusUpdate v1.UpdateJobStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateJob(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save UpdateJob status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "UpdateJob", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for UpdateJob %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchUpdateJobStatus patches only the status of a UpdateJob resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchUpdateJobStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateJob UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateJob not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveUpdateJob(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched UpdateJob status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "UpdateJob", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for UpdateJob %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteUpdateJob deletes a UpdateJob resource
func DeleteUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("UpdateJob UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	updateJob, err := storage.LoadUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("UpdateJob not found: %w", err))
		return
	}

	if err := storage.DeleteUpdateJob(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete UpdateJob: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "UpdateJob", updateJob.Metadata.UID, updateJob.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for UpdateJob %s: %v\n", updateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "UpdateJob deleted successfully",
		UID:     uid,
	})
}
