// Code generated by Fabrica. DO NOT EDIT.
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /firmwareimages (FirmwareImage operations)
//   - /firmwareupdatejobs (FirmwareUpdateJob operations)
//
// Route patterns:
//   - GET    /resource              -> List all resources
//   - GET    /resource/{uid}        -> Get specific resource
//   - POST   /resource              -> Create new resource
//   - PUT    /resource/{uid}        -> Update resource spec
//   - PATCH  /resource/{uid}        -> Patch resource spec
//   - DELETE /resource/{uid}        -> Delete resource
//   - PUT    /resource/{uid}/status -> Update resource status
//   - PATCH  /resource/{uid}/status -> Patch resource status
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/resource"
)

// registerResourcePrefixes registers UID prefixes for all resource types
// This must be called before any resource creation operations
func registerResourcePrefixes() error {

	resource.RegisterResourcePrefix("FirmwareImage", "firmwareimage")

	resource.RegisterResourcePrefix("FirmwareUpdateJob", "firmwareupdatejob")

	return nil
}

// RegisterGeneratedRoutes registers all generated resource routes.
// Note: Middleware should be applied in main.go before calling this function.
// Public service routes such as /health, /openapi.json, and /docs are registered
// in cmd/server/main.go so they remain outside auth middleware.
func RegisterGeneratedRoutes(r chi.Router) {
	// Protected endpoints (resource APIs)
	r.Group(func(protected chi.Router) {

		// FirmwareImage routes
		protected.Route("/firmwareimages", func(r chi.Router) {
			r.Get("/", GetFirmwareImages)
			r.Post("/", CreateFirmwareImage)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetFirmwareImage)
				r.Put("/", UpdateFirmwareImage)
				r.Patch("/", PatchFirmwareImage)
				r.Delete("/", DeleteFirmwareImage)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateFirmwareImageStatus)
					r.Patch("/", PatchFirmwareImageStatus)
				})
			})
		})

		// FirmwareUpdateJob routes
		protected.Route("/firmwareupdatejobs", func(r chi.Router) {
			r.Get("/", GetFirmwareUpdateJobs)
			r.Post("/", CreateFirmwareUpdateJob)
			r.Route("/{uid}", func(r chi.Router) {
				r.Get("/", GetFirmwareUpdateJob)
				r.Put("/", UpdateFirmwareUpdateJob)
				r.Patch("/", PatchFirmwareUpdateJob)
				r.Delete("/", DeleteFirmwareUpdateJob)

				// Status subresource
				r.Route("/status", func(r chi.Router) {
					r.Put("/", UpdateFirmwareUpdateJobStatus)
					r.Patch("/", PatchFirmwareUpdateJobStatus)
				})
			})
		})

	})
}
