// Code generated by Fabrica dev. DO NOT EDIT.
// Template: apiversion/register.gotmpl
// Generated at: 2026-05-01T19:12:36Z
// SPDX-FileCopyrightText: Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
// SPDX-License-Identifier: MIT
//
//

package apiversion

import (
	"github.com/openchami/fabrica/pkg/apiversion"
	"github.com/openchami/fabrica/pkg/versioning"
)

// Registry is the global API version registry
var Registry *apiversion.Registry

func init() {
	Registry = apiversion.NewRegistry()
	Registry.RegisterGroup(apiversion.Group{
		Name:           "hardware.fabrica.dev",
		StorageVersion: "v1",
		Spokes:         []string{"v1"},
	})
	if err := versioning.GlobalVersionRegistry.RegisterVersion("FirmwareImage", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("FirmwareUpdateJob", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
}

// GetRegistry returns the global version registry
func GetRegistry() *apiversion.Registry {
	return Registry
}
