// Code generated by Fabrica dev. DO NOT EDIT.
// Template: server/handlers.go.tmpl
// Generated: 2026-05-01T18:46:17Z
//
// # Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for FirmwareUpdateJob resources.
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'fabrica generate' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /firmwareupdatejobs (list all firmwareupdatejobs)
//   - GET /firmwareupdatejobs/{uid} (get specific FirmwareUpdateJob)
//   - POST /firmwareupdatejobs (create new FirmwareUpdateJob)
//   - PUT /firmwareupdatejobs/{uid} (update FirmwareUpdateJob spec)
//   - PATCH /firmwareupdatejobs/{uid} (patch FirmwareUpdateJob spec)
//   - DELETE /firmwareupdatejobs/{uid} (delete FirmwareUpdateJob)
//   - PUT /firmwareupdatejobs/{uid}/status (update FirmwareUpdateJob status)
//   - PATCH /firmwareupdatejobs/{uid}/status (patch FirmwareUpdateJob status)
//
// Authorization: Add custom middleware for authentication/authorization
// Storage: Uses storage.LoadFirmwareUpdateJob*/SaveFirmwareUpdateJob*/DeleteFirmwareUpdateJob*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Add new version: fabrica add version <group> <version>
//  2. Implement converter: apis/<group>/<version>/converter.go
//  3. Add version-aware storage: storage.LoadFirmwareUpdateJobWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/openchami/fabrica/pkg/events"
	"github.com/openchami/fabrica/pkg/patch"
	"github.com/openchami/fabrica/pkg/resource"
	"github.com/openchami/fabrica/pkg/validation"
	"github.com/openchami/fabrica/pkg/versioning"
	v1 "github.com/user/firmware-manager/apis/hardware.fabrica.dev/v1"

	"github.com/user/firmware-manager/internal/storage"
)

// GetFirmwareUpdateJobs returns all FirmwareUpdateJob resources
func GetFirmwareUpdateJobs(w http.ResponseWriter, r *http.Request) {
	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareupdatejobs, err := storage.LoadAllFirmwareUpdateJobs(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load firmwareupdatejobs: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareupdatejobs)
}

// GetFirmwareUpdateJob returns a specific FirmwareUpdateJob resource by UID
func GetFirmwareUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateJob UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadFirmwareUpdateJob() with version-aware function

	// Authorization: Add custom middleware in routes.go or implement checks here
	// Example: if !authorized(r) { respondError(w, http.StatusUnauthorized, fmt.Errorf("unauthorized")); return }

	firmwareUpdateJob, err := storage.LoadFirmwareUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateJob not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, firmwareUpdateJob)
}

// CreateFirmwareUpdateJob creates a new FirmwareUpdateJob resource
func CreateFirmwareUpdateJob(w http.ResponseWriter, r *http.Request) {
	var req CreateFirmwareUpdateJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Layer 1: Request validation (validates inline spec fields and metadata)
	if err := validation.ValidateResource(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Get version context from request (set by version negotiation middleware)
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("FirmwareUpdateJob")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	// Versioned mode: flat fields with fabrica.Metadata
	firmwareUpdateJob := &v1.FirmwareUpdateJob{
		// Use negotiated ServeVersion (from Accept header) for apiVersion
		APIVersion: versionCtx.ServeVersion,
		Kind:       "FirmwareUpdateJob",
		Spec:       req.AsSpec(),
	}

	// Initialize metadata from request
	firmwareUpdateJob.Metadata = req.Metadata
	firmwareUpdateJob.Metadata.UID = uid
	now := time.Now()
	firmwareUpdateJob.Metadata.CreatedAt = now
	firmwareUpdateJob.Metadata.UpdatedAt = now

	// Set labels and annotations
	if firmwareUpdateJob.Metadata.Labels == nil {
		firmwareUpdateJob.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareUpdateJob.Metadata.Labels[k] = v
	}
	if firmwareUpdateJob.Metadata.Annotations == nil {
		firmwareUpdateJob.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareUpdateJob.Metadata.Annotations[k] = v
	}

	// Layer 2: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), firmwareUpdateJob); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status
	// This assumes the generator passes an 'IsReconcilable' boolean
	// to this template, and that the resource has a .Status.Phase field.

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveFirmwareUpdateJob(r.Context(), firmwareUpdateJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareUpdateJob: %w", err))
		return
	}

	// Publish resource created event

	if err := events.PublishResourceCreated(r.Context(), "FirmwareUpdateJob", firmwareUpdateJob.Metadata.UID, firmwareUpdateJob.Metadata.Name, firmwareUpdateJob); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource created event for FirmwareUpdateJob %s: %v\n", firmwareUpdateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusCreated, firmwareUpdateJob)
}

// UpdateFirmwareUpdateJob updates the spec of an existing FirmwareUpdateJob resource
// NOTE: This endpoint ONLY updates the spec. Use PUT //firmwareupdatejobs/{uid}/status to update status.
func UpdateFirmwareUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateJob UID is required"))
		return
	}

	firmwareUpdateJob, err := storage.LoadFirmwareUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateJob not found: %w", err))
		return
	}

	var req UpdateFirmwareUpdateJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates

	// Versioned mode: direct field access
	if req.Metadata.Name != "" {
		firmwareUpdateJob.Metadata.Name = req.Metadata.Name
	}

	// Update spec fields ONLY - status should use /status subresource
	firmwareUpdateJob.Spec = req.AsSpec()

	// Update labels and annotations
	if firmwareUpdateJob.Metadata.Labels == nil {
		firmwareUpdateJob.Metadata.Labels = make(map[string]string)
	}
	for k, v := range req.Labels {
		firmwareUpdateJob.Metadata.Labels[k] = v
	}
	if firmwareUpdateJob.Metadata.Annotations == nil {
		firmwareUpdateJob.Metadata.Annotations = make(map[string]string)
	}
	for k, v := range req.Annotations {
		firmwareUpdateJob.Metadata.Annotations[k] = v
	}

	// Update timestamp
	firmwareUpdateJob.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareUpdateJob(r.Context(), firmwareUpdateJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareUpdateJob: %w", err))
		return
	}

	// Publish resource updated event
	updateMetadata := map[string]interface{}{
		"updatedAt": firmwareUpdateJob.Metadata.UpdatedAt,
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareUpdateJob", firmwareUpdateJob.Metadata.UID, firmwareUpdateJob.Metadata.Name, firmwareUpdateJob, updateMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource updated event for FirmwareUpdateJob %s: %v\n", firmwareUpdateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareUpdateJob)
}

// PatchFirmwareUpdateJob patches an existing FirmwareUpdateJob resource spec using JSON Merge Patch, JSON Patch, or Shorthand Patch
// Only the spec portion of the resource can be patched - metadata and status are API-managed
func PatchFirmwareUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateJob UID is required"))
		return
	}

	firmwareUpdateJob, err := storage.LoadFirmwareUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateJob not found: %w", err))
		return
	}

	// Read patch document
	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current spec to JSON for patching (only allow spec modifications)
	currentSpecJSON, err := json.Marshal(firmwareUpdateJob.Spec)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current spec: %w", err))
		return
	}

	// Detect patch type from Content-Type header
	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	// Apply patch to spec only
	patchResult, err := patch.ApplyPatchWithOptions(currentSpecJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: true,
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to spec: %w", err))
		return
	}

	// Unmarshal the patched result back to the spec
	if err := json.Unmarshal(patchResult.Updated, &firmwareUpdateJob.Spec); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched spec: %w", err))
		return
	}

	// Touch to update metadata

	firmwareUpdateJob.Metadata.UpdatedAt = time.Now()

	// Save the patched resource
	if err := storage.SaveFirmwareUpdateJob(r.Context(), firmwareUpdateJob); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareUpdateJob: %w", err))
		return
	}

	// Publish resource patched event
	patchMetadata := map[string]interface{}{
		"patchType": patchType,
		"updatedAt": firmwareUpdateJob.Metadata.UpdatedAt,
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareUpdateJob", firmwareUpdateJob.Metadata.UID, firmwareUpdateJob.Metadata.Name, firmwareUpdateJob, patchMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource patched event for FirmwareUpdateJob %s: %v\n", firmwareUpdateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, firmwareUpdateJob)
}

// UpdateFirmwareUpdateJobStatus updates only the status of a FirmwareUpdateJob resource
// This endpoint is intended for controllers, reconcilers, and monitoring systems.
// It does not modify the spec or metadata (except updatedAt timestamp).
//
// Authorization: Requires 'update_status' permission (separate from 'update' permission)
// Events: Publishes resource updated event with updateType: "status"
func UpdateFirmwareUpdateJobStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateJob UID is required"))
		return
	}

	// Authorization: Add custom middleware for status update authorization
	// Status updates can have different permissions than spec updates

	res, err := storage.LoadFirmwareUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateJob not found: %w", err))
		return
	}

	var statusUpdate v1.FirmwareUpdateJobStatus
	if err := json.NewDecoder(r.Body).Decode(&statusUpdate); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid status body: %w", err))
		return
	}

	// Preserve spec - only update status
	res.Status = statusUpdate

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareUpdateJob(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save FirmwareUpdateJob status: %w", err))
		return
	}

	// Publish status update event
	statusMetadata := map[string]interface{}{
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourceUpdated(r.Context(), "FirmwareUpdateJob", res.Metadata.UID, res.Metadata.Name, res, statusMetadata); err != nil {
		// Log but don't fail - events are non-critical
		fmt.Printf("Warning: Failed to publish status update event for FirmwareUpdateJob %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// PatchFirmwareUpdateJobStatus patches only the status of a FirmwareUpdateJob resource
// Supports JSON Merge Patch, JSON Patch, and Shorthand Patch formats.
// Only modifies status fields - spec and metadata are preserved.
func PatchFirmwareUpdateJobStatus(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateJob UID is required"))
		return
	}

	// Authorization: Add custom middleware for status patch authorization
	// Status patches can have different permissions than spec patches

	res, err := storage.LoadFirmwareUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateJob not found: %w", err))
		return
	}

	patchData, err := io.ReadAll(r.Body)
	if err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("failed to read patch data: %w", err))
		return
	}

	// Marshal current status for patching
	currentStatusJSON, err := json.Marshal(res.Status)
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to marshal current status: %w", err))
		return
	}

	contentType := r.Header.Get("Content-Type")
	patchType := patch.DetectPatchType(contentType)

	patchResult, err := patch.ApplyPatchWithOptions(currentStatusJSON, patchData, patchType, patch.PatchOptions{
		AllowAddFields:    true,
		AllowRemoveFields: false, // Don't allow removing status fields
	})
	if err != nil {
		respondError(w, http.StatusUnprocessableEntity, fmt.Errorf("failed to apply patch to status: %w", err))
		return
	}

	// Unmarshal patched status back
	if err := json.Unmarshal(patchResult.Updated, &res.Status); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to unmarshal patched status: %w", err))
		return
	}

	res.Metadata.UpdatedAt = time.Now()

	if err := storage.SaveFirmwareUpdateJob(r.Context(), res); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save patched FirmwareUpdateJob status: %w", err))
		return
	}

	// Publish status patch event
	patchMetadata := map[string]interface{}{
		"patchType":  patchType,
		"updatedAt":  res.Metadata.UpdatedAt,
		"updateType": "status",
	}

	if err := events.PublishResourcePatched(r.Context(), "FirmwareUpdateJob", res.Metadata.UID, res.Metadata.Name, res, patchMetadata); err != nil {
		fmt.Printf("Warning: Failed to publish status patch event for FirmwareUpdateJob %s: %v\n", res.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, res)
}

// DeleteFirmwareUpdateJob deletes a FirmwareUpdateJob resource
func DeleteFirmwareUpdateJob(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("FirmwareUpdateJob UID is required"))
		return
	}

	// Load resource before deletion for event publishing
	firmwareUpdateJob, err := storage.LoadFirmwareUpdateJob(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("FirmwareUpdateJob not found: %w", err))
		return
	}

	if err := storage.DeleteFirmwareUpdateJob(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete FirmwareUpdateJob: %w", err))
		return
	}

	// Publish resource deleted event
	deleteMetadata := map[string]interface{}{
		"deletedAt": time.Now(),
	}

	if err := events.PublishResourceDeleted(r.Context(), "FirmwareUpdateJob", firmwareUpdateJob.Metadata.UID, firmwareUpdateJob.Metadata.Name, deleteMetadata); err != nil {
		// Log the error but don't fail the request - events are non-critical
		fmt.Printf("Warning: Failed to publish resource deleted event for FirmwareUpdateJob %s: %v\n", firmwareUpdateJob.Metadata.UID, err)

	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "FirmwareUpdateJob deleted successfully",
		UID:     uid,
	})
}
